import pandas as pd
import numpy as np
from .core import compute_sMSS


def analyze_track_MSS(df, track_id, v_list=None, plot=False):
    # Analyze a single track to compute the sMSS and optionally plot the trajectory and the gamma vs v curve.
    # df is expected to be a pandas DataFrame containing the tracking data, with columns 'TRACK_ID', 
    # 'POSITION_X', 'POSITION_Y', and 'FRAME'. The positions are expected to be in micrometers (µm) and the time is expected to be in frames.
    # track_id is the ID of the track to analyze. v_list is the list of moments to compute, and plot is
    #  a boolean indicating whether to generate plots.
    # This functions have been designed to work with the .csv files generated by TrackMate, 
    # which have the columns mentioned above. If your data is in a different format, 
    # you may need to modify the code accordingly.

    track = df[df['TRACK_ID'] == track_id]

    traj = track[['POSITION_X','POSITION_Y']].values
    traj = traj

    sMSS, gamma_v_list = compute_sMSS(
        traj,
        v_list=v_list,
        max_lag=len(traj)//3
    )

    corrected = False

    if sMSS < 0 and len(traj) > 3:

        traj = traj[:-1]

        sMSS, gamma_v_list = compute_sMSS(
            traj,
            v_list=v_list,
            max_lag=len(traj)//3
        )

        corrected = True

    if plot:
        from .plotting import plot_trajectory, plot_gamma_vs_v

        if v_list is None:
            v_list = [0,1,2,3,4,5,6]

        plot_trajectory(traj, track_id)
        plot_gamma_vs_v(v_list, gamma_v_list, sMSS)

    return sMSS